Repository googleapis/python-audit-log, pull requests merged in 2021-04, with the labels that each got.

#15 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#16 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  synth.metadata
Labels: cla: yes, context: full, samples

#18 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  synth.metadata
Labels: cla: yes, context: full

#17 chore: prevent normalization of semver versioning
  setup.py
Labels: cla: yes

#19 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: automerge, cla: yes
